import type { Metadata } from 'next';
import SiteFooter from '@/components/site/SiteFooter';
import SiteHeader from '@/components/site/SiteHeader';
import TopUtilityStrip from '@/components/site/TopUtilityStrip';

export const metadata: Metadata = {
  title: 'Beta Terms · Claritas',
  description: 'Terms for using the Claritas closed beta.',
};

const sections = [
  ['Beta service', 'Claritas is an experimental closed-beta product. Features, availability, and data formats may change, and the service may be interrupted or withdrawn. No paid subscription or service-level commitment is offered during beta.'],
  ['Not medical advice', 'Outputs are generated by AI and are not reviewed by a clinician before publication. They may be incomplete, inaccurate, or misleading. Claritas is a research-reading aid, not a medical device, diagnostic service, treatment recommendation, or substitute for the original paper and professional judgment.'],
  ['Your responsibilities', 'Verify every output against the cited source before relying on it. Do not use Claritas for emergency decisions, enter patient-identifiable or confidential data, attempt to disrupt the service, scrape it at abusive rates, or use it unlawfully. You are responsible for activity under your account.'],
  ['Accounts', 'Provide accurate account information and protect access to your email and credentials. You may delete your account from the account page. We may suspend access needed to protect the service or other users.'],
  ['Sources and intellectual property', 'Source papers remain subject to their publishers’ and authors’ rights and licences. Claritas does not grant additional rights to source content. Product code, presentation, and generated organisation remain subject to applicable rights.'],
  ['No warranties', 'The beta is provided as available without warranties of accuracy, fitness for a particular purpose, clinical suitability, uninterrupted availability, or non-infringement, to the extent permitted by law.'],
  ['Liability', 'To the extent permitted by law, the operator is not liable for clinical decisions, patient outcomes, research errors, lost data, or indirect damages arising from use of beta outputs. Rights that cannot legally be excluded remain unaffected.'],
];

export default function TermsPage() {
  return (
    <>
      <TopUtilityStrip />
      <SiteHeader />
      <main className="max-w-[860px] mx-auto px-6 py-12 md:py-16">
        <div className="mono-stat text-teal-deep mb-3">BETA TERMS · 14 JULY 2026</div>
        <h1 className="display text-[44px] md:text-[60px] mb-5">Use the evidence. Keep your judgment.</h1>
        <p className="serif-body text-[17px] text-ink-soft leading-[1.6] mb-10">
          These terms govern the Claritas closed beta. By creating or using an account, you agree to them.
        </p>
        <div className="space-y-8">
          {sections.map(([title, body]) => (
            <section key={title}>
              <h2 className="serif text-[24px] mb-2">{title}</h2>
              <p className="text-[14px] text-ink-soft leading-[1.7]">{body}</p>
            </section>
          ))}
        </div>
      </main>
      <SiteFooter />
    </>
  );
}
