import {
  Activity,
  AlertOctagon,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  Bot,
  Brain,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDot,
  CircleHelp,
  ClipboardList,
  Clock,
  Copy,
  CornerDownRight,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  FileQuestion,
  FileSearch,
  FileText,
  FileX,
  FlaskConical,
  GitFork,
  Globe,
  HeartPulse,
  Image,
  Info,
  KeyRound,
  LayoutDashboard,
  Lightbulb,
  Link as LinkIcon,
  List,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MessageCircle,
  Network,
  Play,
  Plus,
  Quote,
  RefreshCw,
  Scale,
  ScanEye,
  ScanText,
  ScrollText,
  Search,
  SearchX,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldQuestion,
  Shuffle,
  Signal,
  SlidersHorizontal,
  Sparkles,
  Stethoscope,
  Trash2,
  TrendingUp,
  UserRoundSearch,
  Users,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

interface IconProps {
  icon: string;
  className?: string;
  width?: string | number;
  height?: string | number;
}

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  'alert-octagon': AlertOctagon,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  award: Award,
  'badge-check': BadgeCheck,
  'book-open': BookOpen,
  bookmark: Bookmark,
  'bookmark-check': BookmarkCheck,
  bot: Bot,
  brain: Brain,
  'building-2': Building2,
  calendar: Calendar,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  'clipboard-list': ClipboardList,
  clock: Clock,
  copy: Copy,
  'corner-down-right': CornerDownRight,
  'credit-card': CreditCard,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  'file-question': FileQuestion,
  'file-search': FileSearch,
  'file-text': FileText,
  'file-x': FileX,
  'flask-conical': FlaskConical,
  'git-fork': GitFork,
  globe: Globe,
  'heart-pulse': HeartPulse,
  image: Image,
  info: Info,
  'key-round': KeyRound,
  'layout-dashboard': LayoutDashboard,
  lightbulb: Lightbulb,
  link: LinkIcon,
  linkedin: Share2,
  list: List,
  'loader-2': Loader2,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  mail: Mail,
  map: Map,
  'message-circle': MessageCircle,
  network: Network,
  play: Play,
  plus: Plus,
  quote: Quote,
  'refresh-cw': RefreshCw,
  scale: Scale,
  'scan-eye': ScanEye,
  'scan-text': ScanText,
  'scroll-text': ScrollText,
  search: Search,
  'search-x': SearchX,
  'share-2': Share2,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  'shield-question': ShieldQuestion,
  shuffle: Shuffle,
  signal: Signal,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  twitter: Share2,
  'user-round-search': UserRoundSearch,
  users: Users,
  x: X,
  zap: Zap,
};

export default function Icon({ icon, className, width, height }: IconProps) {
  const name = icon.startsWith('lucide:') ? icon.slice('lucide:'.length) : icon;
  const Component = icons[name] ?? CircleHelp;
  return (
    <Component
      aria-hidden="true"
      className={`inline-block shrink-0 align-[-0.125em] ${className ?? ''}`}
      width={width ?? '1em'}
      height={height ?? '1em'}
      focusable="false"
    />
  );
}
