"""Pydantic schemas package.

Re-exports all schemas for convenient imports.
"""

from app.schemas.admin import (
    AdminBackfillResponse,
    AdminHealthResponse,
    AdminIngestResponse,
    AdminPaperListFilters,
    AdminPaperUpdate,
    AdminPasswordResetRequest,
    AdminReindexRequest,
    AdminReindexResponse,
    AdminSingleReindexResponse,
    AdminStatsResponse,
    UserAdminOut,
    UserAdminUpdate,
)
from app.schemas.auth import (
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    LoginResponse,
    LogoutResponse,
    RegisterResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
    TokenOut,
    UserCreate,
    UserLogin,
    UserOut,
)
from app.schemas.common import HealthResponse
from app.schemas.papers import (
    BackfillRequest,
    BackfillResponse,
    FacetsResponse,
    FacetValue,
    FullTextResponse,
    FullTextSection,
    IngestRequest,
    IngestResponse,
    KeyFindingClinical,
    KeyFindingItem,
    KeyFindingsOut,
    MindMapNode,
    MindMapOut,
    PaperDetail,
    PaperListItem,
    PaperListResponse,
    SearchResponse,
    SemanticSearchRequest,
    SemanticSearchResponse,
    SemanticSearchResult,
    VerificationDomains,
    VerificationOut,
)
from app.schemas.user import (
    SavedPaperOut,
    SavedPapersListResponse,
    SavePaperResponse,
)

__all__ = [
    # auth
    "UserCreate",
    "UserLogin",
    "UserOut",
    "TokenOut",
    "LoginResponse",
    "RegisterResponse",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    "LogoutResponse",
    # papers
    "MindMapNode",
    "MindMapOut",
    "KeyFindingClinical",
    "KeyFindingItem",
    "KeyFindingsOut",
    "VerificationDomains",
    "VerificationOut",
    "PaperListItem",
    "FullTextSection",
    "FullTextResponse",
    "FacetValue",
    "FacetsResponse",
    "PaperDetail",
    "PaperListResponse",
    "SearchResponse",
    "SemanticSearchRequest",
    "SemanticSearchResult",
    "SemanticSearchResponse",
    "IngestRequest",
    "IngestResponse",
    "BackfillRequest",
    "BackfillResponse",
    # user
    "SavePaperResponse",
    "SavedPaperOut",
    "SavedPapersListResponse",
    # admin
    "UserAdminOut",
    "UserAdminUpdate",
    "AdminPasswordResetRequest",
    "AdminPaperUpdate",
    "AdminPaperListFilters",
    "AdminStatsResponse",
    "AdminHealthResponse",
    "AdminReindexRequest",
    "AdminReindexResponse",
    "AdminSingleReindexResponse",
    "AdminIngestResponse",
    "AdminBackfillResponse",
    # common
    "HealthResponse",
]
