"""Pydantic schemas for request/response validation — re-exported by domain."""

from schemas.analytics import (
    AnalyticsEventCreate,
    AnalyticsEventOut,
    AnalyticsEventType,
    AnalyticsEventsList,
    AnalyticsEventsQuery,
    AnalyticsOverview,
    AnalyticsPeriod,
    AnalyticsTimeSeries,
    TimeSeriesPoint,
)
from schemas.auth import (
    DeleteAccountResponse,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    LoginResponse,
    LogoutResponse,
    RegisterResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
    TokenOut,
    UserCreate,
    UserLogin,
    UserOut,
)
from schemas.feedback import (
    FeedbackSubmissionResponse,
    ProductFeedbackCreate,
    ProductFeedbackOut,
    ResearchSurveyCreate,
    ResearchSurveyOut,
)
from schemas.health import HealthResponse, ReadinessResponse
from schemas.papers import (
    BackfillRequest,
    BackfillResponse,
    FacetValue,
    FacetsResponse,
    FullTextResponse,
    FullTextSection,
    IngestRequest,
    IngestResponse,
    KeyFindingClinical,
    KeyFindingItem,
    KeyFindingsOut,
    MindMapNode,
    MindMapOut,
    PaperDetail,
    PaperListItem,
    PaperListResponse,
    SearchResponse,
    SemanticSearchRequest,
    SemanticSearchResponse,
    SemanticSearchResult,
    VerificationDomains,
    VerificationOut,
)
from schemas.user import SavePaperResponse, SavedPaperOut, SavedPapersListResponse

__all__ = [
    # analytics
    "AnalyticsEventCreate",
    "AnalyticsEventOut",
    "AnalyticsEventType",
    "AnalyticsEventsList",
    "AnalyticsEventsQuery",
    "AnalyticsOverview",
    "AnalyticsPeriod",
    "AnalyticsTimeSeries",
    "TimeSeriesPoint",
    # auth
    "DeleteAccountResponse",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "LoginResponse",
    "LogoutResponse",
    "RegisterResponse",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    "TokenOut",
    "UserCreate",
    "UserLogin",
    "UserOut",
    # feedback
    "FeedbackSubmissionResponse",
    "ProductFeedbackCreate",
    "ProductFeedbackOut",
    "ResearchSurveyCreate",
    "ResearchSurveyOut",
    # health
    "HealthResponse",
    "ReadinessResponse",
    # papers
    "BackfillRequest",
    "BackfillResponse",
    "FacetValue",
    "FacetsResponse",
    "FullTextResponse",
    "FullTextSection",
    "IngestRequest",
    "IngestResponse",
    "KeyFindingClinical",
    "KeyFindingItem",
    "KeyFindingsOut",
    "MindMapNode",
    "MindMapOut",
    "PaperDetail",
    "PaperListItem",
    "PaperListResponse",
    "SearchResponse",
    "SemanticSearchRequest",
    "SemanticSearchResponse",
    "SemanticSearchResult",
    "VerificationDomains",
    "VerificationOut",
    # user
    "SavePaperResponse",
    "SavedPaperOut",
    "SavedPapersListResponse",
]
